import SwiftUI

struct AboutThisApp: View {
    
    @Environment(\.horizontalSizeClass) var horizontalSizeClass
    
    @AppStorage("isWelcomeSheetShowing") var isWelcomeSheetShowing = true
    
    @State private var courseSeeking: String = "";
    @State private var takingCourse: Bool = false;
    @State private var presentedPage: [CourseView] = [];
    
    @State private var pauseSession: Bool = false;
    
    var body: some View {
        
        ScrollView {
            Section {
                VStack(spacing: 0) {
                    //circle curve
                    Spacer().frame(maxHeight: 500)
                    // Header
                    VStack(alignment: .center) {
                        Spacer()
                            .frame(height: 80)
                        Text("About HearPiano")
                            .frame(maxWidth: .infinity)
                            .font(.system(size: 50))
                            .bold()
                        Divider()
                            .background(Color.white)
                    }
                    //.padding(20)
                    .frame(maxWidth: .infinity)
                    .padding(50)
                    
                    
                    
                }
                
                .background(LinearGradient(gradient: Gradient(colors: [Color.green.opacity(0.5), Color.purple.opacity(0.1)]), startPoint: .bottom, endPoint: .top))
                .offset(y: -70)
                
                
                //                        ProgressionBlock(progression: .constant(0.5))
                //                            .padding()
            }
            
            VStack(alignment: .leading) {
                Text("General Infomation")
                    .font(.title3)
                    .bold()
                Spacer()
                Text("'HearPiano' App created by Sarut Ardnarong (me) and bootstrapped by Empty Swift App Playground on Xcode and developed in Swift Playground App in iPad because Xcode in my MacBook too slow T_T\n")
                
                Text("This app won the Swift Student Challenge - WWDC 2025 (Winner Prize) :)\n")
                
                
                Text("Apologies in advance for incompatible UI and layout for some small device such as iPhone SE and iPhone mini series. I recommended you to use iPad in Landscape mode to get the best experience but iPhone that larger than 6.1 inch will fit perfectly.\n")
                //.padding(20)
                Divider()
                Text("More info about my learning progress")
                    .font(.title3)
                    .bold()
                Spacer()
                Text("I just learn 'Swift' programming language myself")
                Text("I learned since 3 Feb with many source such as YouTube, Stack Overflow and Solve some problem by ChatGPT and coding all by myself\n")
                Divider()
                Text("AI Usage infomation")
                    .font(.title3)
                    .bold()
                Spacer()
                Text("I used ChatGPT to generate 'Ear Training Session' image cover and solve some problems that aren’t done by having the AI ​​write everything. For example, I was prompting “How to make this element top?”")
                Divider()
                Text("Resource and Credit")
                    .font(.title3)
                    .bold()
                Spacer()
                
                Text("'Ear Training Session' cover image generated by ChatGPT through prompt text.")
                
                    .padding()
                    .background(Color.green.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                
                Text("'Customer' character image source [Pixabay under Pixabay Content License](https://pixabay.com/vectors/ai-generated-man-person-obesity-8773213/)")
                
                    .padding()
                    .background(Color.white.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                    .tint(Color.green)
                
                Text("'Piano Tuner' character drawn by Sarut Ardnarong")
                
                    .padding()
                    .background(Color.green.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                
                Text("'House' scene image source [Pixabay under Pixabay Content License](https://pixabay.com/vectors/house-icon-symbol-architecture-2492054/)")
                
                    .padding()
                    .background(Color.white.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                    .tint(Color.green)
                
                Text("'Backpack' image source [Pixabay under Pixabay Content License](https://pixabay.com/vectors/backpack-bag-hiking-trip-travel-145841/)")
                
                    .padding()
                    .background(Color.white.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                    .tint(Color.green)
                
                Text("'Subsonic' SwiftUI Package by Paul Hudson (sound player) [Github](https://github.com/twostraws/Subsonic)")
                
                    .padding()
                    .background(Color.white.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                    .tint(Color.green)
                
                Text("Piano Sound by TEDAgame [Public Domain](https://freesound.org/people/TEDAgame/packs/25405/)")
                
                    .padding()
                    .background(Color.white.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                    .tint(Color.green)
                
                Text("All of sound effect created by Sarut Ardnarong")
                
                    .padding()
                    .background(Color.green.opacity(0.5))
                    .clipShape(.rect(cornerRadius: 20))
                
                
                
                
            }.padding()
            
        }
    }
}
#Preview {
    AboutThisApp()
}
