// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HearPiano",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "HearPiano",
            targets: ["AppModule"],
            bundleIdentifier: "com.sarut.Pianotation",
            teamIdentifier: "47C6UVT3L3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/twostraws/Subsonic", "0.2.0"..<"1.0.0"),
        .package(url: "https://github.com/wvteijlingen/swiftui-interface-orientation.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Subsonic", package: "Subsonic"),
                .product(name: "InterfaceOrientation", package: "swiftui-interface-orientation")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
